### ISSUE TITLE
[v1.3.0|mc1.20.1][v1.3.3|mc1.20.4] Server crash on interaction with the stapler/serger

### ISSUE THREAD

**Issue by hatkidchan** [falkreon/Scarves#10]
Mod version: 1.3.0, also happens on 1.3.3 w/ mc 1.20.4 (#11)

It just crashes the server when I place stapler and interact with it
Also happens with scarf serger.

[crash-2023-12-15_20.53.29-server.txt](https://github.com/falkreon/Scarves/files/13688385/crash-2023-12-15_20.53.29-server.txt)

<details>
<summary>Traceback</summary>

```
[20:53:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: backgroundPainter
        at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:27) ~[libgui-8.0.0+1.20-b459cc0edac6ea68.jar:?]
        at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12) ~[libgui-8.0.0+1.20-b459cc0edac6ea68.jar:?]
        at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:33) ~[libgui-8.0.0+1.20-b459cc0edac6ea68.jar:?]
        at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:53) ~[libgui-8.0.0+1.20-b459cc0edac6ea68.jar:?]
        at blue.endless.scarves.gui.ScarfStaplerGuiDescription.<init>(ScarfStaplerGuiDescription.java:32) ~[scarves-1.3.0.jar:?]
        at blue.endless.scarves.ScarfStaplerBlockEntity.createMenu(ScarfStaplerBlockEntity.java:64) ~[scarves-1.3.0.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[server-intermediary.jar:?]
        at blue.endless.scarves.ScarfStaplerBlock.method_9534(ScarfStaplerBlock.java:50) ~[scarves-1.3.0.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
</details>

<details>
<summary>Server mods</summary>

```
cc-tweaked-1.20.1-fabric-1.109.0.jar
collective-1.20.1-7.16.jar
doubledoors-1.20.1-5.1.jar
fabric-api-0.91.0+1.20.1.jar
fabric-language-kotlin-1.10.16+kotlin.1.9.21.jar
fabric-seasons-2.3+1.20.jar
gentle-picking-1.1.0+fabric-mc1.20.jar
indium-1.0.27+mc1.20.1.jar
jamlib-0.6.1+1.20.x.jar
jei-1.20.1-fabric-15.2.0.27.jar
lithium-fabric-mc1.20.1-0.11.2.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
Plethora-Fabric-1.9.1.jar
right-click-harvest-3.2.3+1.19.x-1.20.1-fabric.jar
scarves-1.3.0.jar
sit-1.20-24.jar
stimber-1.4.0+1.20.1.jar
styled-nicknames-1.2.1+1.20.jar
trinkets-3.7.1.jar
Xaeros_Minimap_23.9.3_Fabric_1.20.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
```
</details>

<details>
<summary>Client mods (probably not important, since it crashes on the server side)</summary>

```
3dskinlayers-fabric-1.5.4-mc1.20.1.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
authme-7.0.2+1.20.jar
badpackets-fabric-0.4.3.jar
balm-fabric-1.20.1-7.2.1.jar
better-clouds-1.3.11+1.20.1.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
bounced-1.20-3.1.1.jar
cc-tweaked-1.20.1-fabric-1.109.0.jar
chat_heads-0.10.27-fabric-1.20.jar
chunksfadein-v1.0.4-1.20.1.jar
cloth-config-11.1.106-fabric.jar
collective-1.20.1-7.16.jar
configured-2.1.1-1.19.4.jar
continuity-3.0.0-beta.4+1.20.1.jar
dark-loading-screen-1.6.14.jar
doubledoors-1.20.1-5.1.jar
dynamic-fps-3.2.1+minecraft-1.20.0.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
exordium-fabric-1.2.1-mc1.20.1.jar
fabric-api-0.91.0+1.20.1.jar
fabric-language-kotlin-1.10.16+kotlin.1.9.21.jar
fabric-seasons-2.3+1.20.jar
fallingleaves-1.15.4+1.20.1.jar
ferritecore-6.0.1-fabric.jar
gentle-picking-1.1.0+fabric-mc1.20.jar
held-item-info-1.5.0.jar
ImmediatelyFast-Fabric-1.2.8+1.20.4.jar
indium-1.0.27+mc1.20.1.jar
inventoryessentials-fabric-1.20.1-8.2.1.jar
iris-mc1.20.1-1.6.11.jar
jamlib-0.6.1+1.20.x.jar
jei-1.20.1-fabric-15.2.0.27.jar
Jump-Sounds-1.4.3.jar
JustEnoughResources-Fabric-1.20.1-1.4.0.238.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
make_bubbles_pop-0.2.0-fabric-mc1.19.4+.jar
modmenu-7.2.2.jar
morechathistory-1.19.1-1.1.1.jar
MouseTweaks-fabric-mc1.20-2.25.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
Plethora-Fabric-1.9.1.jar
right-click-harvest-3.2.3+1.19.x-1.20.1-fabric.jar
scarves-1.3.0.jar
screenshot-to-clipboard-1.0.9-fabric.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
sit-1.20-24.jar
sodium-fabric-mc1.20.1-0.5.3.jar
starlight-1.1.2+fabric.dbc156f.jar
styled-nicknames-1.2.1+1.20.jar
symbol-chat-1.20.1-1.1.2.jar
trinkets-3.7.1.jar
Xaeros_Minimap_23.9.3_Fabric_1.20.jar
XaerosWorldMap_1.37.2_Fabric_1.20.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
Zoomify-2.11.2.jar
```
</details>

Server launch command: `/usr/lib/jvm/java-17-openjdk/bin/java -Xmx2G -jar fabric-server-mc.1.20.1-loader.0.15.2-launcher.0.11.2.jar nogui`

**Comment by falkreon** [comment]
Weird, that stack trace kind of makes it look like it's coming from inside LibGui itself - it shouldn't be classloading BackgroundPainter at all from the server. I'm updating mods anyway, let me do some digging on this.

**Comment by hatkidchan** [comment]
Also happens with scarf ~~table~~ serger, but it's uncraftable, so not sure whether I should even touch it

**Comment by MetalDracon** [comment]
Just noted that the issue that I opened yesterday has about the same error on mod version 1.3.3.

**Comment by hatkidchan** [comment]
so #11 is a dupe?

**Comment by MetalDracon** [comment]
yes a dupe, but on newer versions of game and mod

**Comment by DoloSaber** [comment]
Here's one that reports the exact same error：
At 1.20.1Fabric & scarves-1.3.0
[crash-2024-09-02_14.36.25-server.txt](https://github.com/user-attachments/files/16833229/crash-2024-09-02_14.36.25-server.txt)
